sudo: required
services:
    - docker

before_install:
    - docker build -t brandonwade/docker-react -f Dockerfile.dev .


script:
    - docker run brandonwade/docker-react npm run test -- --coverage
